/* tslint:disable */
export const memory: WebAssembly.Memory;
export function __wbg_rregexp_free(a: number): void;
export function rregexp_new(a: number, b: number): number;
export function rregexp_is_match(a: number, b: number, c: number): number;
export function rregexp_is_match_at(a: number, b: number, c: number, d: number): number;
export function rregexp_find(a: number, b: number, c: number): number;
export function rregexp_find_at(a: number, b: number, c: number, d: number): number;
export function rregexp_find_all(a: number, b: number, c: number): number;
export function rregexp_replace(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function rregexp_replacen(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function rregexp_replace_all(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function rregexp_split(a: number, b: number, c: number): number;
export function rregexp_splitn(a: number, b: number, c: number, d: number): number;
export function rregexp_syntax(a: number): number;
export function get_metadata(): number;
export function __wbindgen_global_argument_ptr(): number;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_free(a: number, b: number): void;
